site_name: AmbrO 的摸鱼空间
site_description: AmbrO的课程笔记、资料整理、学习日程与电影安利

use_directory_urls: true

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - 学习笔记:
      - 电工训:
          - 实验报告: notes/electric_train/first.md
  - 资料下载: resources.md
  - 电影时刻: movies.md
  - 关于我: about.md
